### ISSUE TITLE
highlight for heredoc with file descriptors is broken

### ISSUE THREAD

**Issue by MaxGyver83** [weakish/rcshell.vim#3]
[rc/trip.rc at 2e95de304d1387b26423137deeb7d2db4ebf8143 · rakitzis/rc](https://github.com/rakitzis/rc/blob/2e95de304d1387b26423137deeb7d2db4ebf8143/trip.rc#L125) looks broken, starting in line 125:

![image](https://github.com/weakish/rcshell.vim/assets/13970628/8ea405a9-3c4c-40f7-9c48-0107d6b44344)

Does it look the same for you?

**Comment by weakish** [comment]
Thanks a lot for reporting this issue.
I attempted to fix this in #5.
Please help to review and test it.

**Comment by MaxGyver83** [comment]
Thank you for fixing this!
